### ISSUE TITLE
Can't filter by date

### ISSUE THREAD

**Issue by rohanrichards** [calcinai/xero-php#309]
I'm just trying to do a very basic query where I select invoices within a date range.
I have cut it back to simply trying to get invoices in a specific date, but no matter what I do it refuses to work.
```
$dateString= date('Y-m-d', strtotime('-30 days'));
$invoices = $xero->load('Accounting\\Invoice')
    ->where('Date', $dateString)
    ->where('Status', \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)
    ->page(1)
    ->execute();
foreach($invoices as $invoice) {
    print_r($invoice->getInvoiceNumber() . " | " . $invoice->getDate()->format('d/m/y') . "<br>");
}

>>Fatal error: Uncaught XeroPHP\Remote\Exception\BadRequestException: Operator '==' incompatible with operand types 'DateTime?' and 'String' () Validation errors: in C:\xampp\htdocs\web\eco-dist\src\XeroPHP\Remote\Response.php on line 76
```

If I pass in a raw DateTime object it complains because the second argument of where() is a string.
I've tried using the fromDate() and date() methods on load() as well and they don't seem to filter the data at all.

Here is the string I'm generating using these other methods:
```
https://api.xero.com/api.xro/2.0/Invoices?where=Status%3D%3D%22AUTHORISED%22&order=Date%20DESC&fromDate=2017-09-14&toDate=2017-09-19&page=1
```
Why would this not be filtering by date? It seems ok to me...

Ultimately if someone could just show me how to get all invoices from within a date range I would be very grateful.

**Comment by rohanrichards** [comment]
After some digging I can see that this is actually coming from the response object and is an error that Xero is returning. I will create a post on their forums as I don't think their API should be having any trouble with a date string in their WHERE filters.

**Comment by calcinai** [comment]
This can actually be fixed at this end - it'd probably be better if it was part of the library!

It's just Xero's .net syntax, it's expecting something like:

`   
 ->where('Date', sprintf('DateTime(%s)', $dateString))
`

**Comment by rohanrichards** [comment]
```
        $startDateString = date('Y-m-d');
        $endDateString = date('Y-m-d', strtotime('-5 days'));

        $invoices = $this->xero->load('Accounting\\Invoice')
            ->orderBy("Date", "DESC")
//            ->where('Date>="' . sprintf('DateTime(%s)', $endDateString) . '"')
//            ->where('Date<="' . sprintf('DateTime(%s)', $startDateString) . '"')
            ->where('Date', sprintf('DateTime(%s)', $startDateString))
            ->where('Status', \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)
            ->page($page)
            ->execute();
```

Thanks for the reply @calcinai however none of the above is working for me. Still throwing the same error. Is it something to do with my date strings?

**Comment by calcinai** [comment]
Ah, maybe it's `sprintf('DateTime("%s")', $startDateString)` ?

**Comment by rohanrichards** [comment]
nope...any other ideas?

**Comment by calcinai** [comment]
Actually, see the docs [here](https://developer.xero.com/documentation/api/requests-and-responses), 

> Retrieving a filtered set of resources using the “where” parameter
> ...
> Example 4: Retrieve invoices with an invoice date between a date range
> `Date >= DateTime(2015, 01, 01) && Date < DateTime(2015, 12, 31)`

So that'd make it:

```
$startDateString = date('Y, m, d');
...
->where(sprintf('Date >= DateTime(%s)', startDateString))
```

ew. I'll add proper handling for this now with DateTime objects!

**Comment by rohanrichards** [comment]
Well it's doing _something_. I'm just not sure what, currently if I use:
```
        $dateString = date('Y-m-d', strtotime('-2 days'));
        $invoices = $this->xero->load('Accounting\\Invoice')
            ->where(sprintf('Date < DateTime(%s)', $dateString))
            ->execute();
```
Which I assume should show me everything with a date that is less than 2 days ago (in other words everything from before 2 days ago), I get nothing. If I change it to greater than, I seem to be getting everything, when I'm expecting only things from the last two days.

**Comment by calcinai** [comment]
See my previous comment re: your date string. It's expecting it comma-separated.

**Comment by rohanrichards** [comment]
@calcinai I don't know how I missed that, sorry!
Thank you so much for taking the time to help me nut this out, I really appreciate it. Would you like me to close this issue, or leave it open until you patch for handling DateTime objects?

For completeness, here's the full working code:

```
    function getInvoices($page) {
        $startDateString = date('Y, m, d');
        $endDateString = date('Y, m, d', strtotime('-2 days'));

        $invoices = $this->xero->load('Accounting\\Invoice')
            ->orderBy("Date", "DESC")
            ->where(sprintf('Date >= DateTime(%s) && Date < DateTime(%s)', $endDateString, $startDateString))
            ->where('Status', \XeroPHP\Models\Accounting\Invoice::INVOICE_STATUS_AUTHORISED)
            ->page($page)
            ->execute();

        return $invoices;
    }
```

Seems to be working fine with preliminary testing.

**Comment by nomadme** [comment]
@rohanrichards That was very helpful. This Xero's .net is making me crazy.

**Comment by simontheu** [comment]
Well done!!! Just borrowed this!
